### PR TITLE
nb exploring gas prediction by region

### PR DESCRIPTION
**Pull request by jpeone**

### CODE REVIEW

**Comment by jpeone** [comment]
Just uploading my nb, but want to make sure we are using good git practices.

**Comment by beccacauthorn** [comment]
- I liked the use of the dummy regressor for baseline, this was something I forgot to do in my notebook. 
- I used some other models as well, MLP Regressor and Random Forest. However, they did not perform much better than Linear Regression. 

- Regarding next steps:
- Follow regional modeling as you suggested. Improving model performance and figuring out how to organize locations by region. 
- Figure out how to make predictions further into the future, not regionally focused. For example, in my notebook I added a new column to the dataframe. For week x, I added the price of gas at week x-1. This improved model performance. In this case however, you can only predict gas prices a week in advance. Next steps could be how we can replicate this in a way that allows us to predict prices further into the future. Do you all think this is worth looking into? 

P.S. I have a question: what do you mean when you say this dataset can be accessed via API?

**Comment by jpeone** [comment]
Oh yeah, turns out there are api end points that we can hit, instead of just the xls spreadsheet.  It got me thinking, we could have a refresh endpoint, or set up some refresh logic to refresh our dataset once a week or something.  Just a way to make our project "live" instead of "static".

ty for the suggestions.

**Comment by jpeone** [comment]
https://www.eia.gov/dnav/pet/pet_pri_gnd_dcus_nus_w.htm

If you click the key icon next to a region, or a grade it takes you to an API reference showing exactly what GET request you need to get the most updated info.  Its pretty cool.

**Pull request merged**
